### ISSUE TITLE
failed to make 

### ISSUE THREAD

**Issue by Gerrime** [toniblyx/my-arsenal-of-aws-security-tools#100]
failed to make

**Comment by w0rmr1d3r** [comment]
@toniblyx do you know this person creating issues and PRs lately? For people with notifications enabled of this awesome repository of yours is starting to be annoying...

**Comment by toniblyx** [comment]
I'll block and report it. Sorry for the inconvenience.

**Comment by Gerrime** [comment]
my bad G I am still "learning"

**Comment by Gerrime** [comment]
thank you
