### ISSUE TITLE
aws-extender-cli

### ISSUE THREAD

**Issue by noraj** [toniblyx/my-arsenal-of-aws-security-tools#17]
You may be interested https://github.com/VirtueSecurity/aws-extender-cli

**Comment by toniblyx** [comment]
Added. Thanks @noraj

**Comment by noraj** [comment]
@toniblyx You're welcome. I even added the tool to BlackArch if you are an ArchLLinux user: https://github.com/BlackArch/blackarch/pull/2253/files

**Comment by toniblyx** [comment]
Cool!
