### ISSUE TITLE
Wrong/missing Link 

### ISSUE THREAD

**Issue by BBoSec** [toniblyx/my-arsenal-of-aws-security-tools#19]
The link of Training-> flAWS 2 should be http://flaws2.cloud/ and not something like: https://github.com/toniblyx/my-arsenal-of-aws-security-tools/blob/master/flaws2.cloud

**Comment by toniblyx** [comment]
Thanks @BBoSec, I’ll fix it ASAP. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by toniblyx** [comment]
fixed in b508211 thanks
