### ISSUE TITLE
submit to awesome

### ISSUE THREAD

**Issue by mdaniel** [toniblyx/my-arsenal-of-aws-security-tools#20]
While this project doesn't strictly speaking advertise itself as ["awesome"](https://github.com/topics/awesome), it seems like a great candidate for inclusion in [the awesome list](https://github.com/sindresorhus/awesome)

**Comment by toniblyx** [comment]
Thanks @mdaniel that’s a good idea, I’ll see how can I make it. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by coffeewithayman** [comment]
+1 that idea. I didn't see one a few months ago and decided to create [one](https://github.com/C8H10N4OO/awesome-aws-security) up to spec, but then found yours @toniblyx so I stopped and didn't submit, lol. Nice work. Feel free to take anything from there that's not on your list.

**Comment by toniblyx** [comment]
I have checked out their requirements at https://github.com/sindresorhus/awesome/blob/master/pull_request_template.md and my current list doesn't pass them, too much work to make it ideal for them. 
@C8H10N4OO thanks for sharing your list, I think all the tools you have are already in here. Thanks!
