### ISSUE TITLE
Humour: Unfortunate project naming

### ISSUE THREAD

**Issue by rob42** [toniblyx/my-arsenal-of-aws-security-tools#29]
Nice project, great work. 
But I noticed an unfortunate abbreviation in my firefox home page today..
![image](https://user-images.githubusercontent.com/3239261/72010368-9a2b7080-32bc-11ea-8e3f-31d6de98fe7f.png)

LOL 
Rob

**Comment by toniblyx** [comment]
Lol I’ll have to file a claim to Mozilla 😜

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
