### ISSUE TITLE
my-arsenal-of-aws-security-tools

### ISSUE THREAD

**Issue by oracle85-oss** [toniblyx/my-arsenal-of-aws-security-tools#56]
Hi, I wonder if you can help me, please. I install my-arsenal-of-aws-security-tools, after I create the AWS AMI and EC2 Instances using packet etc. I have access to the AWS instances, I can see the file my-arsenal-of-aws-security-tools and folder, however, I do not know how to use the tools already configure inside my-arsenal-of-aws-security-tools? is there any command I need to type to access the tools, etc?
Yours sincerely

**Comment by toniblyx** [comment]
Hi @oracle85-oss sorry for the misunderstanding, that code is just sample code to show how to start building your own AMI with all these packages and tools, if you look at the code doesn't do much but a guide on how it could be done.

**Comment by oracle85-oss** [comment]
Hi thanks for your prompt response ,yes I create the AMI with all these package and tools, however , how can I have access to these tools,or I will have to install each single tools? On this AMI?
Thanks

**Comment by toniblyx** [comment]
each tool has its own way to be installed, so you will have probably to create that code per tool in packer. Of course, the easy part is to do a `git clone http://github.com/$whatever/$repo` but the installation and usage itself depends on each one.

**Comment by oracle85-oss** [comment]
Hi thanks for your help !!
