### ISSUE TITLE
Additional Cloud Resources for Learning - Podcast & Newsletter

### ISSUE THREAD

**Issue by hashishrajan** [toniblyx/my-arsenal-of-aws-security-tools#59]
First of all, I just wanted to say, awesome job on maintaining such an awesome resources of all kinds of security tools.

The resources listed here are going to be valuable for a long time. However, I noticed there were no newsletter/podcast listed in the repo, which can be great resources for those wanting to stay upto date with cloud security on a weekly basis.
 
I have found the following two resources helpful and this would great resources for your audience too looking at learning Cloud Security and keeping updated.

### **Weekly Newsletter:**
Cloud Security Newsletter: https://cloudseclist.com/
- Weekly Newsletter about everything happening from security perspective in Public Clouds. This newsletter is by Marco Lancini (who also maintains Cartography)

### **Weekly Podcast:**
**Cloud Security Podcast:** www.cloudsecuritypodcast.tv
- Cloud Security Podcast is a weekly podcast that interviews Cloud Security Practitioners from companies in Public Cloud like Netflix, Atlassian, AWS, Microsoft, CapitalOne, Hashicorp, to name few of the previous guest. I think your community would find the interview valuable.

Full Disclosure, i am the producer and host of Cloud Security Podcast, which I have run for the community with the aim to help more folks learn and upskill in Cloud Security by listening to methods and lessons of other experienced practitioners

**Comment by toniblyx** [comment]
Done, thanks

**Comment by hashishrajan** [comment]
Thanks Toni! My name has a typo, it's Ashish Rajan. The name in the repo says Hashish Rajan!

**Comment by toniblyx** [comment]
Fixed :) sorry about that
