### ISSUE TITLE
Honeytoken tools in training

### ISSUE THREAD

**Issue by 0xdabbad00** [toniblyx/my-arsenal-of-aws-security-tools#6]
The following are listed as training:
https://bitbucket.org/asecurityteam/spacecrab
https://breachinsider.com/honey-buckets/

Those should be moved to a "honeytoken" section.  

Additionally for honeytokens you could add https://github.com/0x4D31/honeyLambda and https://canarytokens.org/generate (opensourced at https://github.com/thinkst/canarytokens-docker , not AWS specific is the easiest way to create AWS key honeytokens).

**Comment by toniblyx** [comment]
Thanks @0xdabbad00. Done :)
