### ISSUE TITLE
Please include this tool as open source https://github.com/aisecuremecyber/threatspotter

### ISSUE THREAD

**Issue by aisecuremecyber** [toniblyx/my-arsenal-of-aws-security-tools#74]
The AISecureMe ThreatSpotter is an implementation of community edition and scans for containers and images.

The main community features that AISecureMe ThreatSpotter is supporting:

Data Visibility: All virtual machines, containers, Kubernetes clusters, running processes, and interrelated connections are visible at one place on provided credentials.
Vulnerability Management: Initiate scans on the attached container and images for provided AWS credentials.
Runtime Compliance Scan: Perform compliance scan for containers and images for provided AWS credentials.
Container Scanning: Perform vulnerability scans on images stored in AWS ECR and provide accurate results.
Integration with DevOps pipelines.
Visualization: Visualize Kubernetes clusters, virtual machines, containers and images, running processes, and network connections in near real-time.
Runtime Vulnerability Management: Perform vulnerability scans on localhosts.
Runtime Vulnerability Management: Perform vulnerability scans on running containers & container images
Container Registry Scanning: Check for vulnerabilities in images stored on AWS ECR.
CI/CD pipeline: CircleCI.

**Comment by toniblyx** [comment]
I don't see anywhere the open source license of that project, please update the repo and feel free to send a PR to include your solution.
