### ISSUE TITLE
Suggestion to call repository awesome-oss-aws-security-tools

### ISSUE THREAD

**Issue by dlorch** [toniblyx/my-arsenal-of-aws-security-tools#76]
It has become sort of a common naming to call repositories "awesome" for curated lists of everything "awesome" around a given topic. Idea therefore to rename this repository to awesome-oss-aws-security-tools or awesome-aws-security-tools.

Overview: https://github.com/topics/awesome

Examples:
* https://github.com/vinta/awesome-python
* https://github.com/avelino/awesome-go
* https://github.com/sindresorhus/awesome-nodejs

**Comment by toniblyx** [comment]
Thanks for the suggestion @dlorch, I like this format more than the awesome format to be honest and I don't plan to change the format so far. However, feel free to do your own with the resources found here. My goal with this repo is to have my own list to look at of what exist for AWS security in terms of Open Source tooling and help others to identify those tools and use them to make their workloads more secure so the more lists or collections we have the better for the whole community (hence safer internet, I guess)

**Comment by dlorch** [comment]
Absolutely, thanks for reviewing the suggestion.
