### ISSUE TITLE
Suggestion: Remove visible URL column

### ISSUE THREAD

**Issue by DannyBen** [toniblyx/my-arsenal-of-aws-security-tools#82]
This is a great list, but especially since Github added the wide righthand sidebar, the table columns are too narrow for the content they display.

How about removing the URL column, and simply adding it as a link to the package name?

## Before

![image](https://user-images.githubusercontent.com/2405099/157234209-1d972d5a-2d54-4a03-8036-3d65802ca6ae.png)

![image](https://user-images.githubusercontent.com/2405099/157234225-3916d203-903c-412c-b91f-d6b046a3cbb3.png)

### Example in Markdown

---

## Before

| Name | URL | Description | Popularity | Metadata |
| ---------- | :---------- | :---------- | :----------: | :----------: |
| **ScoutSuite** | [https://github.com/nccgroup/ScoutSuite](https://github.com/nccgroup/ScoutSuite) | Multi-Cloud Security auditing tool for AWS Google Cloud and Azure environments (python) |[![stars](https://badgen.net/github/stars/nccgroup/ScoutSuite)](https://badgen.net/github/stars/nccgroup/ScoutSuite)| [![contributors](https://badgen.net/github/contributors/nccgroup/ScoutSuite)](https://badgen.net/github/contributors/nccgroup/ScoutSuite)[![watchers](https://badgen.net/github/watchers/nccgroup/ScoutSuite)](https://badgen.net/github/watchers/nccgroup/ScoutSuite)[![last-commit](https://badgen.net/github/last-commit/nccgroup/ScoutSuite)](https://badgen.net/github/last-commit/nccgroup/ScoutSuite) [![open-issues](https://badgen.net/github/open-issues/nccgroup/ScoutSuite)](https://badgen.net/github/open-issues/nccgroup/ScoutSuite) [![closed-issues](https://badgen.net/github/closed-issues/nccgroup/ScoutSuite)](https://badgen.net/github/closed-issues/nccgroup/ScoutSuite) |
| **Prowler** | [https://github.com/toniblyx/prowler](https://github.com/toniblyx/prowler) | CIS benchmarks and additional checks for security best practices in AWS (bash and python components) |[![stars](https://badgen.net/github/stars/toniblyx/prowler)](https://badgen.net/github/stars/toniblyx/prowler)| [![contributors](https://badgen.net/github/contributors/toniblyx/prowler)](https://badgen.net/github/contributors/toniblyx/prowler)[![watchers](https://badgen.net/github/watchers/toniblyx/prowler)](https://badgen.net/github/watchers/toniblyx/prowler)[![last-commit](https://badgen.net/github/last-commit/toniblyx/prowler)](https://badgen.net/github/last-commit/toniblyx/prowler) [![open-issues](https://badgen.net/github/open-issues/toniblyx/prowler)](https://badgen.net/github/open-issues/toniblyx/prowler) [![closed-issues](https://badgen.net/github/closed-issues/toniblyx/prowler)](https://badgen.net/github/closed-issues/toniblyx/prowler) |

## After

| Name | Description | Popularity | Metadata |
| ---------- | :---------- | :----------: | :----------: |
| [ScoutSuite](https://github.com/nccgroup/ScoutSuite) | Multi-Cloud Security auditing tool for AWS Google Cloud and Azure environments (python) |[![stars](https://badgen.net/github/stars/nccgroup/ScoutSuite)](https://badgen.net/github/stars/nccgroup/ScoutSuite)| [![contributors](https://badgen.net/github/contributors/nccgroup/ScoutSuite)](https://badgen.net/github/contributors/nccgroup/ScoutSuite)[![watchers](https://badgen.net/github/watchers/nccgroup/ScoutSuite)](https://badgen.net/github/watchers/nccgroup/ScoutSuite)[![last-commit](https://badgen.net/github/last-commit/nccgroup/ScoutSuite)](https://badgen.net/github/last-commit/nccgroup/ScoutSuite) [![open-issues](https://badgen.net/github/open-issues/nccgroup/ScoutSuite)](https://badgen.net/github/open-issues/nccgroup/ScoutSuite) [![closed-issues](https://badgen.net/github/closed-issues/nccgroup/ScoutSuite)](https://badgen.net/github/closed-issues/nccgroup/ScoutSuite) |
| [Prowler](https://github.com/toniblyx/prowler) | CIS benchmarks and additional checks for security best practices in AWS (bash and python components) |[![stars](https://badgen.net/github/stars/toniblyx/prowler)](https://badgen.net/github/stars/toniblyx/prowler)| [![contributors](https://badgen.net/github/contributors/toniblyx/prowler)](https://badgen.net/github/contributors/toniblyx/prowler)[![watchers](https://badgen.net/github/watchers/toniblyx/prowler)](https://badgen.net/github/watchers/toniblyx/prowler)[![last-commit](https://badgen.net/github/last-commit/toniblyx/prowler)](https://badgen.net/github/last-commit/toniblyx/prowler) [![open-issues](https://badgen.net/github/open-issues/toniblyx/prowler)](https://badgen.net/github/open-issues/toniblyx/prowler) [![closed-issues](https://badgen.net/github/closed-issues/toniblyx/prowler)](https://badgen.net/github/closed-issues/toniblyx/prowler) |

---

**Comment by toniblyx** [comment]
Yeah, that makes sense. Since there are so many tools in the list, that will take time to change. If you like, please feel free to send a PR with those changes. Thanks!

**Comment by DannyBen** [comment]
Done. Viewing the diff in that PR is nearly impossible, so I suggest a second eye on the final result before merging (the change was done by automation, not by hand).
