### ISSUE TITLE
Add Falco for runtime monitoring (EKS, Fargate ECS and plain instances)

### ISSUE THREAD

**Issue by manuelbcd** [toniblyx/my-arsenal-of-aws-security-tools#83]
Hello, I'm a little bit confused since I don't see any specific tool for runtime security. 
Would it make sense to add Falco? It is an Open Source tool to secure containers, clusters and VMs, captures runtime events and trigger actions (alerts, integrations) based on it powerful rule engine.

I can do the PR but I would like to check first that I'm not missing anything here, is there any reason for non adding Falco?

FYI @toniblyx 

Thank you

**Comment by toniblyx** [comment]
Hi @manuelbcd, I'm not adding container related tools or solutions to this list, but probably is time to do so in a separate category. Would you mind to send a PR with that? Thanks in advance.

**Comment by ACRavelo** [comment]
I can have it done by a programming AI.
