### ISSUE TITLE
Submit to the security tools list

### ISSUE THREAD

**Issue by v8blink** [toniblyx/my-arsenal-of-aws-security-tools#88]
Name: Cyclops
Description: The Cyclops is a web browser with XSS detection feature, it is chromium-based xss detection that used to find the flows from a source to  a sink.
github:https://github.com/v8blink/Chromium-based-XSS-Taint-Tracking/blob/main/README-en.md

**Comment by toniblyx** [comment]
thanks @v8blink however this is not related to the topic of this repo.
